In [1]:
import pandas as pd
import json
import numpy as np

## Load Datasets

In [2]:
# restaurant data
restaurants_df = pd.read_csv("data/Uber_Eats_data.csv")

In [6]:
restaurants_df.tail()

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
23188,Izakaya Gastro Pub,Yes,Yes,3.8 /5,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean","1,200",Pubs and bars,Whitefield
23189,M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9 /5,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,"2,000",Pubs and bars,Whitefield
23190,Keys Cafe - Keys Hotel,No,No,2.8 /5,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian","1,200",Pubs and bars,Whitefield
23191,Bhagini,No,No,2.5 /5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs and bars,Whitefield
23192,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500",Pubs and bars,Whitefield

In [7]:
restaurants_df.info()
print("\n----------------------------------------\n")
restaurants_df.shape

<class 'pandas.DataFrame'>
RangeIndex: 23193 entries, 0 to 23192
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         23193 non-null  str
 1   online_order                 23193 non-null  str
 2   book_table                   23193 non-null  str
 3   rate                         23193 non-null  str
 4   votes                        23193 non-null  int64
 5   phone                        23193 non-null  str
 6   location                     23193 non-null  str
 7   rest_type                    23193 non-null  str
 8   dish_liked                   23193 non-null  str
 9   cuisines                     23193 non-null  str
 10  approx_cost(for two people)  23193 non-null  str
 11  listed_in(type)              23193 non-null  str
 12  listed_in(city)              23193 non-null  str
dtypes: int64(1), str(12)
memory usage: 6.5 MB

----------------------------------------

(23193, 13)

In [8]:
restaurants_df.isnull().sum()

name                           0
online_order                   0
book_table                     0
rate                           0
votes                          0
phone                          0
location                       0
rest_type                      0
dish_liked                     0
cuisines                       0
approx_cost(for two people)    0
listed_in(type)                0
listed_in(city)                0
dtype: int64

In [9]:
restaurants_df.duplicated().sum()

np.int64(35)

In [10]:
restaurants_df["phone"].sample(20)

8671       080 26711554\r\n+91 9741406338
15987          080 26784129\n080 26912010
15909          080 26845444\n080 26846444
7271                       +91 7012891601
20690                        080 49653251
8080     +91 9902000045\r\n+91 9902000031
17994        +91 9606030004\n080 23461077
16417                      +91 7204196666
9112                       +91 9243493482
13657                        080 49652469
14066    +91 9606796336\r\n+91 9686799482
8640       080 41462929\r\n+91 8598866594
818      +91 9880438170\r\n+91 9880661701
13413                      +91 9141678224
20000      +91 9902920066\n+91 9986667679
14249    +91 8040940831\r\n+91 8606621987
21414          080 41148428\n080 41148810
16876      +91 9972402570\n+91 9844094505
2415     +91 9538892287\r\n+91 9900514899
21255        +91 8861300580\n080 22233666
Name: phone, dtype: str

In [11]:
restaurants_df["approx_cost(for two people)"].unique()

<ArrowStringArray>
[  '800',   '300',   '600',   '700',   '550',   '500',   '450',   '650',
   '400',   '750',   '200',   '850', '1,200',   '150',   '350',   '250',
 '1,500', '1,300', '1,000',   '100',   '900', '1,100', '1,600',   '950',
   '230', '1,700', '1,400', '1,350', '2,200', '2,000', '1,800', '1,900',
   '180',   '330', '2,500', '2,100', '3,000', '2,800', '3,400',    '40',
 '1,250', '3,500', '4,000', '2,400', '1,450', '3,200', '6,000', '1,050',
 '4,100', '2,300',   '120', '2,600', '5,000', '3,700', '1,650', '2,700',
 '4,500']
Length: 57, dtype: str

In [12]:
restaurants_df["rate"].value_counts()["NEW"]

np.int64(147)

## Data Pre-Processing

In [13]:
# remove duplicated rows
restaurants_df = restaurants_df.drop_duplicates()

In [14]:
# normalize rate column
restaurants_df['rate'] = (restaurants_df['rate'].str.replace("/5","").str.strip().replace("NEW", np.nan))

In [15]:
# convert rate column to numeric
restaurants_df['rate'] = pd.to_numeric(restaurants_df["rate"])

In [16]:
# normalize approx_cost column
restaurants_df["approx_cost(for two people)"] = (restaurants_df["approx_cost(for two people)"].str.replace(",","").str.strip())

In [17]:
# convert approx_cost column to numeric
restaurants_df["approx_cost(for two people)"] = pd.to_numeric(restaurants_df["approx_cost(for two people)"])

In [18]:
restaurants_df.info()

<class 'pandas.DataFrame'>
Index: 23158 entries, 0 to 23192
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         23158 non-null  str
 1   online_order                 23158 non-null  str
 2   book_table                   23158 non-null  str
 3   rate                         23012 non-null  float64
 4   votes                        23158 non-null  int64
 5   phone                        23158 non-null  str
 6   location                     23158 non-null  str
 7   rest_type                    23158 non-null  str
 8   dish_liked                   23158 non-null  str
 9   cuisines                     23158 non-null  str
 10  approx_cost(for two people)  23158 non-null  int64
 11  listed_in(type)              23158 non-null  str
 12  listed_in(city)              23158 non-null  str
dtypes: float64(1), int64(2), str(10)
memory usage: 6.5 MB

## Feature Engineering

In [19]:
# analyze cost distribution to create pricing buckets
restaurants_df["approx_cost(for two people)"] .describe()

count    23158.000000
mean       755.274203
std        521.079298
min         40.000000
25%        400.000000
50%        600.000000
75%       1000.000000
max       6000.000000
Name: approx_cost(for two people), dtype: float64

In [20]:
# function to map pricing segment
def map_pricing_segment(cost):
    if(pd.isna(cost)):
        return "Unknown"
    elif cost <= 400:
        return "Budget"
    elif cost <= 600:
        return "Mid Range"
    elif cost <= 1000:
        return "Premium"
    else:
        return "Elite"

# function to map ratings category
def map_ratings(rating):
    if pd.isna(rating):
        return "Unrated"
    elif rating < 3:
        return "Poor"
    elif rating >= 3 and rating <= 4:
        return "Good"
    else:
        return "Excellent"

In [21]:
# create new column and map segments
restaurants_df["pricing_segment"] = restaurants_df["approx_cost(for two people)"].apply(map_pricing_segment)

In [22]:
# similarly create new column bucket for ratings
restaurants_df['ratings_category'] = restaurants_df['rate'].apply(map_ratings)

In [23]:
restaurants_df[['rate','ratings_category']].sample(20)

       rate ratings_category
14071   2.8             Poor
19485   4.1        Excellent
20755   3.5             Good
811     3.6             Good
22371   4.2        Excellent
15435   4.4        Excellent
2246    3.9             Good
5639    4.2        Excellent
17600   4.3        Excellent
6280    3.6             Good
373     4.2        Excellent
20023   4.0             Good
2204    4.0             Good
16283   3.8             Good
17946   4.1        Excellent
5067    4.3        Excellent
385     4.0             Good
7198    3.7             Good
22632   2.9             Poor
21216   3.7             Good

In [24]:
restaurants_df.isnull().sum()

name                             0
online_order                     0
book_table                       0
rate                           146
votes                            0
phone                            0
location                         0
rest_type                        0
dish_liked                       0
cuisines                         0
approx_cost(for two people)      0
listed_in(type)                  0
listed_in(city)                  0
pricing_segment                  0
ratings_category                 0
dtype: int64

In [25]:
# renaming columns
restaurants_df = restaurants_df.rename(
    columns = {
        'approx_cost(for two people)': 'approx_cost_for_two',
        'listed_in(type)': 'listed_in_type',
        'listed_in(city)': 'listed_in_city'
    }
)

## Save the transformed data into new csv file

In [26]:
restaurants_df.to_csv(
    "cleaned_restaurants.csv",
    index=False
)

In [27]:
cleaned_df = pd.read_csv("cleaned_restaurants.csv")

cleaned_df.info()
cleaned_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 23158 entries, 0 to 23157
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   name                 23158 non-null  str
 1   online_order         23158 non-null  str
 2   book_table           23158 non-null  str
 3   rate                 23012 non-null  float64
 4   votes                23158 non-null  int64
 5   phone                23158 non-null  str
 6   location             23158 non-null  str
 7   rest_type            23158 non-null  str
 8   dish_liked           23158 non-null  str
 9   cuisines             23158 non-null  str
 10  approx_cost_for_two  23158 non-null  int64
 11  listed_in_type       23158 non-null  str
 12  listed_in_city       23158 non-null  str
 13  pricing_segment      23158 non-null  str
 14  ratings_category     23158 non-null  str
dtypes: float64(1), int64(2), str(12)
memory usage: 6.9 MB

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost_for_two,listed_in_type,listed_in_city,pricing_segment,ratings_category
0,Jalsa,Yes,Yes,4.1,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari,Premium,Excellent
1,Spice Elephant,Yes,No,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari,Premium,Excellent
2,San Churro Cafe,Yes,No,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari,Premium,Good
3,Addhuri Udupi Bhojana,No,No,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari,Budget,Good
4,Grand Village,No,No,3.8,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari,Mid Range,Good

## Establish SQL Connection

In [11]:
from sqlalchemy import create_engine, text

username = "postgres"
password = "rishi"
port = "5432"
host = "localhost"
database = "uber_eats_db"

conn_string = f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"

try:
    engine = create_engine(conn_string)
    with engine.connect() as conn:
        result = conn.execute(text("SELECT version();"))
        print(f"Postgressql version: {result.fetchone()}")
        
except Exception as e:
    print("Connection failed", e)

Postgressql version: ('PostgreSQL 18.3 on x86_64-windows, compiled by msvc-19.44.35223, 64-bit',)

## Create Schema

In [32]:
query = '''
CREATE TABLE restaurants (
    restaurant_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    online_order VARCHAR(5),
    book_table VARCHAR(5),
    rate NUMERIC(3,1),
    votes INTEGER,
    phone TEXT,
    location VARCHAR(100),
    rest_type TEXT,
    dish_liked TEXT,
    cuisines TEXT,
    approx_cost_for_two INTEGER,
    listed_in_type VARCHAR(100),
    listed_in_city VARCHAR(100),
    pricing_segment VARCHAR(20),
    ratings_category VARCHAR(20)
);
'''

# with engine.connect() as conn:
#     conn.execute(text(query))
#     conn.commit()

## Insert records

In [33]:
# cleaned_df.to_sql(
#     'restaurants',
#     engine,
#     if_exists = 'append',
#     index = False
# )

158

In [43]:
fetch_data = """
SELECT
    COUNT(*) AS total_rows,
    COUNT(rate) AS rated_restaurants
FROM restaurants;
"""

sample = pd.read_sql(fetch_data, engine)
sample

   total_rows  rated_restaurants
0       23158              23012

## Resolve Business Queries

### Which Bangalore locations have the highest average restaurant ratings?

In [47]:
# Changing float type format globally
pd.options.display.float_format = '{:.1f}'.format

In [48]:
q1 = """
SELECT location, AVG(rate) as avg_ratings, ratings_category
FROM restaurants
WHERE rate is NOT NULL
GROUP BY location, ratings_category
ORDER BY avg_ratings DESC
"""

q1_result = pd.read_sql(q1, engine)
q1_result

           location  avg_ratings ratings_category
0       City Market          4.4        Excellent
1         Banaswadi          4.4        Excellent
2       Koramangala          4.4        Excellent
3          Nagawara          4.3        Excellent
4            Hennur          4.3        Excellent
..              ...          ...              ...
205   Kaggadasapura          2.4             Poor
206    Bommanahalli          2.3             Poor
207   Richmond Road          2.3             Poor
208  Residency Road          2.2             Poor
209   Church Street          1.8             Poor

[210 rows x 3 columns]

### Which locations are over-saturated with restaurants?

In [50]:
q2 = """
SELECT location, COUNT(location) as total_restaurants
FROM restaurants
GROUP BY location
ORDER BY total_restaurants DESC
"""

q2_result = pd.read_sql(q2, engine)
q2_result

                 location  total_restaurants
0   Koramangala 5th Block               1782
1                     BTM               1454
2             Indiranagar               1346
3                     HSR               1161
4               Jayanagar               1037
..                    ...                ...
83         West Bangalore                  2
84   Rajarajeshwari Nagar                  2
85            Magadi Road                  2
86        Kanakapura Road                  2
87               KR Puram                  1

[88 rows x 2 columns]

### Does online ordering improve restaurant ratings?

In [56]:
q3 = """
SELECT online_order, ROUND(AVG(rate), 2) AS avg_rating, COUNT(*) AS restaurant_count
FROM restaurants
WHERE rate IS NOT NULL
GROUP BY online_order;
"""

q3_result = pd.read_sql(q3, engine)
q3_result

  online_order  avg_rating  restaurant_count
0           No         3.9              6738
1          Yes         3.9             16274

### Does table booking correlate with higher customer ratings?

In [58]:
q4 = """
SELECT book_table as table_booking, ROUND(AVG(rate), 2) AS avg_rating, COUNT(*) AS restaurant_count
FROM restaurants
WHERE rate IS NOT NULL
GROUP BY table_booking;
"""

q4_result = pd.read_sql(q4, engine)
q4_result

  table_booking  avg_rating  restaurant_count
0            No         3.8             16991
1           Yes         4.2              6021

### What price range delivers the best customer satisfaction?

In [70]:
q5 = """
SELECT AVG(approx_cost_for_two) as avg_cost_for_two, rate as ratings, pricing_segment
FROM restaurants
WHERE rate is NOT NULL
GROUP BY ratings, pricing_segment
ORDER BY ratings DESC
"""

q5_result = pd.read_sql(q5, engine)
q5_result

     avg_cost_for_two  ratings pricing_segment
0              1000.0      4.9         Premium
1              1587.5      4.9           Elite
2               400.0      4.9          Budget
3              1630.0      4.8           Elite
4              1000.0      4.8         Premium
..                ...      ...             ...
108             650.0      2.1         Premium
109             360.0      2.1          Budget
110            1500.0      2.0           Elite
111             800.0      2.0         Premium
112            1200.0      1.8           Elite

[113 rows x 3 columns]

### How do low, mid, and premium-priced restaurants perform in terms of ratings?

In [63]:
q6 = """
SELECT
    pricing_segment,
    ROUND(AVG(rate), 2) AS avg_rating,
    COUNT(*) AS restaurant_count
FROM restaurants
WHERE rate IS NOT NULL
GROUP BY pricing_segment
ORDER BY avg_rating DESC;
"""

q6_result = pd.read_sql(q6, engine)
q6_result

  pricing_segment  avg_rating  restaurant_count
0           Elite         4.2              4677
1         Premium         3.9              5983
2          Budget         3.8              6764
3       Mid Range         3.8              5588

### Which cuisines are most common in Bangalore?

In [71]:
q7 = """
SELECT
    cuisines,
    COUNT(*) AS restaurant_count
FROM restaurants
GROUP BY cuisines
ORDER BY restaurant_count DESC
LIMIT 10;
"""

q7_result = pd.read_sql(q7, engine)
q7_result

                              cuisines  restaurant_count
0                         North Indian              1144
1                North Indian, Chinese               776
2                         South Indian               359
3                                 Cafe               273
4  South Indian, North Indian, Chinese               233
5                     Bakery, Desserts               215
6                  Desserts, Beverages               214
7                              Chinese               210
8                  Ice Cream, Desserts               208
9                             Desserts               206

### Which cuisines receive the highest average ratings?

In [75]:
q8 = """
SELECT
    cuisines,
    ROUND(AVG(rate), 2) AS avg_rating,
    COUNT(*) AS restaurant_count
FROM restaurants
WHERE rate IS NOT NULL
GROUP BY cuisines
HAVING COUNT(*) >= 20
ORDER BY avg_rating DESC
LIMIT 10;
"""

q8_result = pd.read_sql(q8, engine)
q8_result

,cuisines,avg_rating,restaurant_count
0,"Continental, Asian, North Indian",4.7,21
1,"North Indian, Thai, Japanese, Continental, Cafe",4.7,34
2,"American, North Indian, Chinese, Finger Food",4.6,24
3,"Cafe, American, Burger, Steak",4.6,43
4,"North Indian, European, Mediterranean, BBQ, Kebab",4.5,39
5,"Italian, Pizza, Salad",4.5,28
6,"European, Continental",4.5,23
7,"Cafe, Desserts, Continental",4.5,24
8,"Ice Cream, Cafe, Pizza, Burger, Desserts, Beve...",4.4,33
9,"Italian, Salad",4.4,40

### Which cuisines perform well despite having fewer restaurants?

In [76]:
q9 = """
SELECT
    cuisines,
    COUNT(*) AS restaurant_count,
    ROUND(AVG(rate), 2) AS avg_rating
FROM restaurants
WHERE rate IS NOT NULL
GROUP BY cuisines
HAVING COUNT(*) BETWEEN 20 AND 100
ORDER BY avg_rating DESC;
"""

q9_result = pd.read_sql(q9, engine)
q9_result

,cuisines,restaurant_count,avg_rating
0,"Continental, Asian, North Indian",21,4.7
1,"North Indian, Thai, Japanese, Continental, Cafe",34,4.7
2,"Cafe, American, Burger, Steak",43,4.6
3,"American, North Indian, Chinese, Finger Food",24,4.6
4,"North Indian, European, Mediterranean, BBQ, Kebab",39,4.5
...,...,...,...
202,"South Indian, North Indian, Chinese, Street Fo...",32,3.1
203,"North Indian, Street Food, Mithai",23,3.1
204,"Bakery, Fast Food, Italian",26,3.1
205,"North Indian, Chinese, Andhra",22,3.0
206,"Chinese, South Indian, North Indian",36,3.0

### What is the relationship between restaurant cost and rating?

In [77]:
q10 = """
SELECT
    pricing_segment,
    ROUND(AVG(rate), 2) AS avg_rating,
    ROUND(AVG(votes), 0) AS avg_votes,
    COUNT(*) AS restaurant_count
FROM restaurants
WHERE rate IS NOT NULL
GROUP BY pricing_segment
ORDER BY AVG(approx_cost_for_two);
"""

q10_result = pd.read_sql(q10, engine)
q10_result

  pricing_segment  avg_rating  avg_votes  restaurant_count
0          Budget         3.8      209.0              6764
1       Mid Range         3.8      426.0              5588
2         Premium         3.9      652.0              5983
3           Elite         4.2     1326.0              4677

## Orders Dataset

In [3]:
# order data
orders_df = pd.read_json("data/orders.json")

## Data Understanding

In [10]:
orders_df.head()

,order_id,restaurant_name,order_date,order_value,discount_used,payment_method
0,8174c2af-07a4-4837-9068-1169d963e36e,TBC Sky Lounge,2025-05-06,201.87,No,Card
1,0f9ddb57-4632-4a9f-9afe-1d2e41b94e32,KC Das - Sweet Paradise,2026-01-08,1392.27,No,Cash
2,099deda6-8c53-41cb-abf8-00126e6b2643,Hotel Kadamba Veg,2026-01-22,1358.35,Yes,UPI
3,94a6ba27-d6ef-4d10-a026-ac0c0afa8505,Cafe Srinidhi,2025-11-10,782.37,No,UPI
4,216f3ec7-80a9-4d95-872f-715c37163b6d,Pebble,2025-12-22,1551.09,Yes,UPI

In [15]:
orders_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         25000 non-null  object
 1   restaurant_name  25000 non-null  str
 2   order_date       25000 non-null  datetime64[us]
 3   order_value      25000 non-null  float64
 4   discount_used    25000 non-null  str
 5   payment_method   25000 non-null  str
dtypes: datetime64[us](1), float64(1), object(1), str(3)
memory usage: 1.7+ MB

In [14]:
orders_df.isnull().sum()

order_id           0
restaurant_name    0
order_date         0
order_value        0
discount_used      0
payment_method     0
dtype: int64

## Pre Processing

In [8]:
# convert date column from string to datetime
orders_df["order_date"] = pd.to_datetime(
    orders_df["order_date"]
)

In [13]:
# convert order_id to GUID from string
import uuid

orders_df["order_id"] = orders_df["order_id"].apply(uuid.UUID)

In [12]:
orders_df.duplicated().sum()

np.int64(0)

## Create Orders Schema

In [16]:
order_query = """
CREATE TABLE orders(
    order_id UUID PRIMARY KEY,
    restaurant_name VARCHAR(255) NOT NULL,
    order_date DATE NOT NULL,
    order_value NUMERIC(10,2) NOT NULL,
    discount_used VARCHAR(5) NOT NULL,
    payment_method VARCHAR(20) NOT NULL
);
"""

# with engine.connect() as conn:
#     conn.execute(text(order_query))
#     conn.commit()

## Migrate Orders Data

In [17]:
# orders_df.to_csv(
#     "cleaned_orders.csv",
#     index=False
# )

In [18]:
# orders_df.to_sql(
#     'orders',
#     engine,
#     if_exists="append",
#     index = False
# )

1000

## Business queries for Orders

### Which restaurants generate the highest order revenue?

In [ ]:
q11 = """
SELECT
    restaurant_name,
    ROUND(SUM(order_value), 2) AS total_revenue,
    COUNT(*) AS total_orders
FROM orders
GROUP BY restaurant_name
ORDER BY total_revenue DESC
LIMIT 10;
"""

q11_result = pd.read_sql(q11, engine)
q11_result

### Which months receive the highest number of orders?

In [21]:
q12 = """
SELECT
    TO_CHAR(order_date, 'MONTH') AS month,
    COUNT(*) AS total_orders
FROM orders
GROUP BY month
ORDER BY total_orders DESC;
"""

q12_result = pd.read_sql(q12, engine)
q12_result

        month  total_orders
0   DECEMBER           2664
1   JANUARY            2642
2   JULY               2613
3   MAY                2592
4   OCTOBER            2531
5   AUGUST             2520
6   SEPTEMBER          2483
7   NOVEMBER           2478
8   JUNE               2422
9   FEBRUARY           1903
10  APRIL               152

### Do discounts increase customer spending?

In [25]:
q13 = """
SELECT
    discount_used,
    ROUND(AVG(order_value), 2) AS avg_order_value,
    COUNT(*) AS total_orders
FROM orders
GROUP BY discount_used;
"""

q13_result = pd.read_sql(q13, engine)
q13_result

  discount_used  avg_order_value  total_orders
0            No           822.49         12509
1           Yes          1149.91         12491

### Which payment methods are most preferred?

In [24]:
q14 = """
SELECT
    payment_method,
    COUNT(*) AS total_orders,
    ROUND(AVG(order_value), 2) AS avg_order_value
FROM orders
GROUP BY payment_method
ORDER BY total_orders DESC;
"""

q14_result = pd.read_sql(q14, engine)
q14_result

  payment_method  total_orders  avg_order_value
0           Cash          8384           983.47
1           Card          8364           989.02
2            UPI          8252           985.75

### Which restaurants have the highest average order value?

In [23]:
q15 = """
SELECT
    restaurant_name,
    ROUND(AVG(order_value), 2) AS avg_order_value,
    COUNT(*) AS total_orders
FROM orders
GROUP BY restaurant_name
ORDER BY avg_order_value DESC
LIMIT 10;
"""

q15_result = pd.read_sql(q15, engine)
q15_result

,restaurant_name,avg_order_value,total_orders
0,Chatori Tongue,1690.90,5
1,1441 Pizzeria,1625.12,2
2,Shagun Sweets & Foods,1614.57,2
3,Chow San,1610.83,5
4,Nando's,1593.40,4
5,Chaiwala,1593.30,4
6,Moto Store & CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃ...,1589.89,4
7,Biting Junction,1572.31,5
8,Bikaner Jn,1554.20,5
9,Salt - Indian Restaurant Bar & Grill,1550.47,2